version: '3.8'

services:
  postgres-vault:
    image: postgres:15-alpine
    container_name: postgres-vault
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thesis2026
      POSTGRES_DB: pigeondb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ingestion-api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: ingestion-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:thesis2026@postgres-vault:5432/pigeondb
    depends_on:
      - postgres-vault

volumes:
  postgres_data:
